apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remote-debug-helper-router-deployment-role
  namespace: openshift-ingress
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "watch"]
